### ISSUE TITLE
error when trying to copy db

### ISSUE THREAD

**Issue by jstoebel** [jstoebel/epub_tools#11]
user reported this error: 

```
redacted_user@MacBooks-MacBook-Air  ~/code/esmagazine   master ●  epub copy_db
/Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/2.1.0/psych.rb:464:in `initialize': Is a directory @ io_fillbuf - fd:7 /Users/redacted_user/.epub_tools.yml (Errno::EISDIR)
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/2.1.0/psych.rb:464:in `open'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/2.1.0/psych.rb:464:in `load_file'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.5/lib/cli_base.rb:25:in `parse_config_file'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.5/lib/cli_base.rb:16:in `options'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.0/lib/thor.rb:236:in `block in subcommand'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
    from /Users/redacted_user/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.5/exe/epub:5:in `<top (required)>'
    from /Users/redacted_user/.rbenv/versions/2.1.7/bin/epub:23:in `load'
```

**Comment by jstoebel** [comment]
looks like the user may have made a directory called `.epub_tools.yml`
