### ISSUE TITLE
bash: bundle: command not found

### ISSUE THREAD

**Issue by jstoebel** [jstoebel/epub_tools#22]
When trying to dump the production database for SCB I'm getting an error:
```
ssh jstoebel@rails-app-105 "cd /web/project/supplychainbrain_production/current && bundle exec rake db:backup"
bash: bundle: command not found
```

But If I ssh in and then issue the command it works

```
➜  supplychainbrain git:(master) ✗ ssh jstoebel@rails-app-105 "cd /web/project/supplychainbrain_production/current"
➜  supplychainbrain git:(master) ✗ bundle # no errors

**Comment by jstoebel** [comment]
Confirmed that this is working as intended (TM). 

ssh user@host "some command here" starts a non-interactive shell.  This means that your environment is not loaded.

You'll have to provide the full path to bundle when you do things like that.

**Comment by jstoebel** [comment]
getting this error

```
ssh jstoebel@rails-stage-app-6 "cd /web/project/supplychainbrain_staging/current && /opt/ruby-2.1.7/bin/bundle exec rake db:backup --trace

** Invoke db:backup (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Access denied for user 'supplychainbrain'@'localhost' (using password: YES)
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
/opt/ruby-2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
/opt/ruby-2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/model_schema.rb:310:in `clear_cache!'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.4/lib/active_record/railtie.rb:103:in `block (2 levels) in <class:Railtie>'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.4/lib/active_support/callbacks.rb:418:in `_run__980315572139713286__prepare__3826855482874983772__callbacks'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.4/lib/active_support/callbacks.rb:405:in `__run_callback'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.4/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.22.4/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.22.4/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/application/finisher.rb:47:in `block in <module:Finisher>'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:30:in `instance_exec'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:30:in `run'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:54:in `each'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/initializable.rb:54:in `run_initializers'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/application.rb:136:in `initialize!'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/railtie/configurable.rb:30:in `method_missing'
/web/project/supplychainbrain_staging/releases/20181205021757/config/environment.rb:5:in `<top (required)>'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `block in require'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:236:in `load_dependency'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/activesupport-3.2.22.4/lib/active_support/dependencies.rb:251:in `require'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/application.rb:103:in `require_environment!'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/railties-3.2.22.4/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/opt/ruby-2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/opt/ruby-2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/bin/rake:23:in `load'
/web/project/supplychainbrain_staging/shared/bundle/ruby/2.1.0/bin/rake:23:in `<top (required)>'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/opt/ruby-2.1.7/lib/ruby/gems/2.1.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/opt/ruby-2.1.7/bin/bundle:23:in `load'
/opt/ruby-2.1.7/bin/bundle:23:in `<main>'
Tasks: TOP => db:backup => environmentLoading Rails environment for Resque
```
