### ISSUE TITLE
failed copy_db on ngi stage

### ISSUE THREAD

**Issue by jstoebel** [jstoebel/epub_tools#35]
failed to load mysql on ngi stage

```
/Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.9/lib/epub_tools/cli/copy_db.rb:123:in `load_to_mysql': mysql failed to load script (RuntimeError)
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.9/lib/epub_tools/cli/copy_db.rb:110:in `process_dump_file'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.9/lib/epub_tools/cli/copy_db.rb:54:in `dump_and_process'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.9/lib/epub_tools/cli/copy_db.rb:25:in `copy_db'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.9/exe/epub:5:in `<top (required)>'
	from /Users/jstoebel/.rbenv/versions/2.1.7/bin/epub:23:in `load'
	from /Users/jstoebel/.rbenv/versions/2.1.7/bin/epub:23:in `<main>'
```

**Comment by jstoebel** [comment]
wasn't tried with latest build

**Comment by jstoebel** [comment]
tried with latest build. could not reproduce.
