### ISSUE TITLE
http error when trying to watch build for jade branch

### ISSUE THREAD

**Issue by jstoebel** [jstoebel/epub_tools#58]
```
➜  jade git:(lint_fixes) ✗ epub status watch
/Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.12/lib/jenkins/project.rb:55:in `check_http_error!': Not Found (RuntimeError)
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.12/lib/jenkins/project.rb:25:in `fetch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.12/lib/epub_tools/cli/status.rb:50:in `fetch_and_report'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.12/lib/epub_tools/cli/status.rb:27:in `watch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.12/exe/epub:5:in `<top (required)>'
	from /Users/jstoebel/.rbenv/versions/2.1.7/bin/epub:23:in `load'
	from /Users/jstoebel/.rbenv/versions/2.1.7/bin/epub:23:in `<main>'
```

**Comment by jstoebel** [comment]
maybe the endpoint was derived incorrectly

**Comment by jstoebel** [comment]
let's log the endpoint

**Comment by jstoebel** [comment]
couldn't reproduce. maybe this branch was removed after being merged?

**Comment by jstoebel** [comment]
here's an example of the issue
```
➜  jade_bnp git:(cr/interior_polls) ✗ epub status report
/Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.15/lib/jenkins/project.rb:55:in `check_http_error!': Not Found (RuntimeError)
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.15/lib/jenkins/project.rb:25:in `fetch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.15/lib/epub_tools/cli/status.rb:50:in `fetch_and_report'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.15/lib/epub_tools/cli/status.rb:19:in `report'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Users/jstoebel/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/epub_tools-0.1.15/exe/epub:5:in `<top (required)>'
	from /Users/jstoebel/.rbenv/versions/2.1.7/bin/epub:23:in `load'
	from /Users/jstoebel/.rbenv/versions/2.1.7/bin/epub:23:in `<main>'
```
